jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pci -DskipAssembly

        '
name: Build Test
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
